package agents

import (
	"context"
	"fmt"

	"github.com/AniruthKarthik/llm-orchestrator/internal/core"
)

// PlannedTask represents a task generated by the planner.
type PlannedTask struct {
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	Description  string            `json:"description"`
	Input        map[string]any    `json:"input"`
	Dependencies []string          `json:"dependencies"`
	AgentID      string            `json:"agent_id"`
	OutputSchema map[string]string `json:"output_schema"`
}

// ExecutionPlan represents the full graph generated by the planner.
type ExecutionPlan struct {
	WorkflowID  string        `json:"workflow_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Tasks       []PlannedTask `json:"tasks"`
}

// Planner manages the dynamic generation of workflows.
type Planner struct {
	agentRegistry *AgentRegistry
}

func NewPlanner(r *AgentRegistry) *Planner {
	return &Planner{
		agentRegistry: r,
	}
}

// GeneratePlan takes an objective and uses a planner agent to create an execution plan.
func (p *Planner) GeneratePlan(ctx context.Context, agentID string, objective string) (*ExecutionPlan, error) {
	agent, exists := p.agentRegistry.Get(agentID)
	if !exists {
		return nil, fmt.Errorf("planner agent not found: %s", agentID)
	}

	if agent.Role != RolePlanner {
		return nil, fmt.Errorf("agent %s is not a planner", agentID)
	}

	// In a real implementation, we would call the LLM here.
	// The prompt would include the objective and instructions to output JSON matching ExecutionPlan.
	
	// Simulated LLM response for now
	plan := &ExecutionPlan{
		WorkflowID:  core.NewID(), // Assuming core.NewID() exists or similar
		Name:        "Planned Workflow for: " + objective,
		Description: "Dynamically generated plan",
		Tasks: []PlannedTask{
			{
				ID:          "task-1",
				Name:        "research-task",
				Description: "Researching " + objective,
				Input:       map[string]any{"query": objective},
			},
			{
				ID:           "task-2",
				Name:         "summarize-task",
				Description:  "Summarizing results",
				Dependencies: []string{"task-1"},
			},
		},
	}

	return plan, nil
}

// CompilePlan converts an ExecutionPlan into a runtime Workflow.
func (p *Planner) CompilePlan(plan *ExecutionPlan) *core.Workflow {
	workflow := core.NewWorkflow(plan.WorkflowID, plan.Name, plan.Description)
	
	for _, pt := range plan.Tasks {
		task := core.NewTask(pt.ID, pt.Name, pt.Description, pt.Input, pt.Dependencies)
		if pt.AgentID != "" {
			task.WithAgentID(pt.AgentID)
		}
		if pt.OutputSchema != nil {
			task.WithOutputSchema(pt.OutputSchema)
		}
		workflow.AddTask(task)
	}

	return workflow
}
